#-------------------------------
# General Site Settings
title: Samuel Isaías Calderón Aguirre
logo: logo2.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Samuel Isaías Calderón Aguirre
  image: profile2.jpg
  say-hello: Hello, I’m <strong>Samuel Isaías Calderón Aguirre</strong>
  bio: <strong>Systems engineer</strong>, I have worked as an <strong>IT support technician</strong> and <strong>Jr. systems administrator</strong>. I am currently studying <strong>Machine Learning</strong> and <strong>Artificial Intelligence</strong>. Passionate about the world of <strong>Linux</strong> and <strong>open source</strong>. I study <strong>Gnostic knowledge</strong> as a philosophy of life for personal development.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: samcalderonaguirre # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
