#-------------------------------
# General Site Settings
title: Samuel Isaías Calderón Aguirre
logo: logo2.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Samuel Isaías Calderón Aguirre
  image: profile2.jpg
  say-hello: Hello, I’m <strong>Samuel Calderón</strong>
  bio: <strong>Systems engineer</strong>, IT support technician and Jr. systems administrator. <strong>Machine Learning</strong> and <strong>Artificial Intelligence</strong> student. Passionate about the world of <strong>Linux</strong> and <strong>open source</strong>.


#-------------------------------
# Contact links
twitter: https://twitter.com/samcalderonag23 # Add your Twitter handle
facebook: https://facebook.com/sam.calderonaguirre
github: https://github.com/samcalderonaguirre
instagram: https://instagram.com/samcalderonaguirre
linkedin: https://linkedin.com/in/samcalderonaguirre1996


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: samcalderonaguirre # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
