#-------------------------------
# General Site Settings
title: SAM TECH
logo: logo5.svg # You can add own logo.
description: Soluciones tecnológicas a tu alcance. Tecnología sin límites, soporte sin preocupaciones


#-------------------------------
# Author Settings
author:
  name: SAM TECH
  image: profile7.png
  say-hello: <strong>SAM TECH</strong>
  bio: Soluciones rápidas y confiables en Soporte Técnico y TI


#-------------------------------
# Contact links
twitter: https://twitter.com/samcalderonag23 # Add your Twitter handle
facebook: https://www.facebook.com/sam.tech.ecuador/
github: https://github.com/samcalderonaguirre
instagram: https://www.instagram.com/samtechec/
linkedin: https://linkedin.com/in/samcalderonaguirre1996


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https://samcalderonaguirre-github-io # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
